### ISSUE TITLE
El ejercicio esta desaprobado

### ISSUE THREAD

**Issue by yosbel-penate** [lazaroariel02/LLave#1]
No hay una interfaz de usuario que permita al usuario insertar datos, no existe un crud funcional.
Los elementos de la view esta ligados a los del negocio.

**Comment by lazaroariel02** [comment]
Ok profe profe pero en ese ejercicio en ningún lugar dice q hay q crear algún tipo de interfaz
De hecho en los objetivos de aprendizaje del problema dice q saldrás conociendo q es una clase abstracta y q son métodos abstractos

**Comment by yosbel-penate** [comment]
a esta altura del curso eso se infiere

**Comment by lazaroariel02** [comment]
Ok como usted diga igual ya hice lo q pidió
